version: '3.8'

services:
  bot:
    build: .
    container_name: compease_bot
    restart: always
    env_file:
      - .env
    # Или можно указать переменные явно:
    # environment:
    #   - BOT_TOKEN=${BOT_TOKEN}
    #   - SUPABASE_URL=${SUPABASE_URL}
    #   - SUPABASE_KEY=${SUPABASE_KEY}
